{"timestamp": "2025-05-14T18:57:38.820129", "level": "ERROR", "message": "Exception in APIRootView: Authentication credentials were not provided.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "NotAuthenticated", "value": "Authentication credentials were not provided.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 503, in dispatch\n    self.initial(request, *args, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/sentry_sdk/integrations/django/__init__.py\", line 331, in sentry_patched_drf_initial\n    return old_drf_initial(self, request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 421, in initial\n    self.check_permissions(request)\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 339, in check_permissions\n    self.permission_denied(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        request,\n        ^^^^^^^^\n        message=getattr(permission, 'message', None),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        code=getattr(permission, 'code', None)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 180, in permission_denied\n    raise exceptions.NotAuthenticated()\n", "rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.\n"]}, "request_id": "9da02e14-6305-4a0e-90ec-f31888e1506d", "extra": {"view": "APIRootView", "request": {"method": "GET", "path": "/api/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "NotAuthenticated"}}
{"timestamp": "2025-05-14T18:58:19.895548", "level": "ERROR", "message": "Exception in TokenObtainPairView: Method \"GET\" not allowed.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "MethodNotAllowed", "value": "Method \"GET\" not allowed.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 173, in http_method_not_allowed\n    raise exceptions.MethodNotAllowed(request.method)\n", "rest_framework.exceptions.MethodNotAllowed: Method \"GET\" not allowed.\n"]}, "request_id": "59a06aa4-838d-4da5-8958-1c03c2398023", "extra": {"view": "TokenObtainPairView", "request": {"method": "GET", "path": "/api/token/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "MethodNotAllowed"}}
{"timestamp": "2025-05-14T18:58:20.678646", "level": "ERROR", "message": "Exception in TokenObtainPairView: Method \"GET\" not allowed.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "MethodNotAllowed", "value": "Method \"GET\" not allowed.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 173, in http_method_not_allowed\n    raise exceptions.MethodNotAllowed(request.method)\n", "rest_framework.exceptions.MethodNotAllowed: Method \"GET\" not allowed.\n"]}, "request_id": "648d557a-5d3e-472b-8220-c5bb0014b2f7", "extra": {"view": "TokenObtainPairView", "request": {"method": "GET", "path": "/api/token/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "MethodNotAllowed"}}
{"timestamp": "2025-05-14T18:58:37.446095", "level": "ERROR", "message": "Exception in TokenObtainPairView: No active account found with the given credentials", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "AuthenticationFailed", "value": "No active account found with the given credentials", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework_simplejwt/views.py\", line 44, in post\n    serializer.is_valid(raise_exception=True)\n    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/serializers.py\", line 225, in is_valid\n    self._validated_data = self.run_validation(self.initial_data)\n                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/serializers.py\", line 447, in run_validation\n    value = self.validate(value)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework_simplejwt/serializers.py\", line 73, in validate\n    data = super().validate(attrs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework_simplejwt/serializers.py\", line 57, in validate\n    raise exceptions.AuthenticationFailed(\n    ...<2 lines>...\n    )\n", "rest_framework.exceptions.AuthenticationFailed: No active account found with the given credentials\n"]}, "request_id": "b2e04175-1bd3-40c1-89ea-f264fa6f31d4", "extra": {"view": "TokenObtainPairView", "request": {"method": "POST", "path": "/api/token/", "query_params": {}, "content_type": "multipart/form-data; boundary=----WebKitFormBoundaryFdcagGLzNJSFy93I", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "AuthenticationFailed"}}
{"timestamp": "2025-05-14T19:10:13.926857", "level": "ERROR", "message": "Exception in APIRootView: Authentication credentials were not provided.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "NotAuthenticated", "value": "Authentication credentials were not provided.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 503, in dispatch\n    self.initial(request, *args, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/sentry_sdk/integrations/django/__init__.py\", line 331, in sentry_patched_drf_initial\n    return old_drf_initial(self, request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 421, in initial\n    self.check_permissions(request)\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 339, in check_permissions\n    self.permission_denied(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        request,\n        ^^^^^^^^\n        message=getattr(permission, 'message', None),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        code=getattr(permission, 'code', None)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 180, in permission_denied\n    raise exceptions.NotAuthenticated()\n", "rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.\n"]}, "request_id": "882c5dd5-ff27-40a6-9ed0-4021d735308c", "extra": {"view": "APIRootView", "request": {"method": "GET", "path": "/api/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "NotAuthenticated"}}
{"timestamp": "2025-05-15T12:55:25.678476", "level": "ERROR", "message": "Exception in APIRootView: Authentication credentials were not provided.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "NotAuthenticated", "value": "Authentication credentials were not provided.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 503, in dispatch\n    self.initial(request, *args, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/sentry_sdk/integrations/django/__init__.py\", line 331, in sentry_patched_drf_initial\n    return old_drf_initial(self, request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 421, in initial\n    self.check_permissions(request)\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 339, in check_permissions\n    self.permission_denied(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        request,\n        ^^^^^^^^\n        message=getattr(permission, 'message', None),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        code=getattr(permission, 'code', None)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 180, in permission_denied\n    raise exceptions.NotAuthenticated()\n", "rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.\n"]}, "request_id": "131fae49-d7bd-463b-8f3e-2e9515450c27", "extra": {"view": "APIRootView", "request": {"method": "GET", "path": "/api/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "NotAuthenticated"}}
{"timestamp": "2025-05-15T13:16:09.309065", "level": "ERROR", "message": "Exception in APIRootView: Authentication credentials were not provided.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "NotAuthenticated", "value": "Authentication credentials were not provided.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 503, in dispatch\n    self.initial(request, *args, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/sentry_sdk/integrations/django/__init__.py\", line 331, in sentry_patched_drf_initial\n    return old_drf_initial(self, request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 421, in initial\n    self.check_permissions(request)\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 339, in check_permissions\n    self.permission_denied(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        request,\n        ^^^^^^^^\n        message=getattr(permission, 'message', None),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        code=getattr(permission, 'code', None)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 180, in permission_denied\n    raise exceptions.NotAuthenticated()\n", "rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.\n"]}, "request_id": "2374361d-28c7-4ea3-b5d4-69e40743443b", "extra": {"view": "APIRootView", "request": {"method": "GET", "path": "/api/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "NotAuthenticated"}}
{"timestamp": "2025-05-15T15:40:48.361962", "level": "ERROR", "message": "Exception in APIRootView: Authentication credentials were not provided.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "NotAuthenticated", "value": "Authentication credentials were not provided.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 503, in dispatch\n    self.initial(request, *args, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/sentry_sdk/integrations/django/__init__.py\", line 331, in sentry_patched_drf_initial\n    return old_drf_initial(self, request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 421, in initial\n    self.check_permissions(request)\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 339, in check_permissions\n    self.permission_denied(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        request,\n        ^^^^^^^^\n        message=getattr(permission, 'message', None),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        code=getattr(permission, 'code', None)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 180, in permission_denied\n    raise exceptions.NotAuthenticated()\n", "rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.\n"]}, "request_id": "22f3ec12-3b74-4956-9c5a-4692b6c80da4", "extra": {"view": "APIRootView", "request": {"method": "GET", "path": "/api/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "NotAuthenticated"}}
{"timestamp": "2025-05-15T15:41:13.555766", "level": "ERROR", "message": "Exception in APIRootView: Authentication credentials were not provided.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "NotAuthenticated", "value": "Authentication credentials were not provided.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 503, in dispatch\n    self.initial(request, *args, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/sentry_sdk/integrations/django/__init__.py\", line 331, in sentry_patched_drf_initial\n    return old_drf_initial(self, request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 421, in initial\n    self.check_permissions(request)\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 339, in check_permissions\n    self.permission_denied(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        request,\n        ^^^^^^^^\n        message=getattr(permission, 'message', None),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        code=getattr(permission, 'code', None)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 180, in permission_denied\n    raise exceptions.NotAuthenticated()\n", "rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.\n"]}, "request_id": "1ec788a5-c0f0-4b6d-bd5d-f7e0b2be9524", "extra": {"view": "APIRootView", "request": {"method": "GET", "path": "/api/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "NotAuthenticated"}}
{"timestamp": "2025-05-15T15:41:39.687655", "level": "ERROR", "message": "Exception in APIRootView: Authentication credentials were not provided.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "NotAuthenticated", "value": "Authentication credentials were not provided.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 503, in dispatch\n    self.initial(request, *args, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/sentry_sdk/integrations/django/__init__.py\", line 331, in sentry_patched_drf_initial\n    return old_drf_initial(self, request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 421, in initial\n    self.check_permissions(request)\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 339, in check_permissions\n    self.permission_denied(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        request,\n        ^^^^^^^^\n        message=getattr(permission, 'message', None),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        code=getattr(permission, 'code', None)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 180, in permission_denied\n    raise exceptions.NotAuthenticated()\n", "rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.\n"]}, "request_id": "c50f4f1b-eb8f-49f5-b6ef-cb0b5687cfcc", "extra": {"view": "APIRootView", "request": {"method": "GET", "path": "/api/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "NotAuthenticated"}}
{"timestamp": "2025-05-15T15:41:41.513818", "level": "ERROR", "message": "Exception in APIRootView: Authentication credentials were not provided.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "NotAuthenticated", "value": "Authentication credentials were not provided.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 503, in dispatch\n    self.initial(request, *args, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/sentry_sdk/integrations/django/__init__.py\", line 331, in sentry_patched_drf_initial\n    return old_drf_initial(self, request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 421, in initial\n    self.check_permissions(request)\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 339, in check_permissions\n    self.permission_denied(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        request,\n        ^^^^^^^^\n        message=getattr(permission, 'message', None),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        code=getattr(permission, 'code', None)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 180, in permission_denied\n    raise exceptions.NotAuthenticated()\n", "rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.\n"]}, "request_id": "71c5b570-963b-4a5e-a360-ffa7f820cc32", "extra": {"view": "APIRootView", "request": {"method": "GET", "path": "/api/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "NotAuthenticated"}}
{"timestamp": "2025-05-15T15:41:44.098212", "level": "ERROR", "message": "Exception in TokenObtainPairView: Method \"GET\" not allowed.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "MethodNotAllowed", "value": "Method \"GET\" not allowed.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 173, in http_method_not_allowed\n    raise exceptions.MethodNotAllowed(request.method)\n", "rest_framework.exceptions.MethodNotAllowed: Method \"GET\" not allowed.\n"]}, "request_id": "a0718e31-9787-4a66-b9fe-82fccecb6716", "extra": {"view": "TokenObtainPairView", "request": {"method": "GET", "path": "/api/token/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "MethodNotAllowed"}}
{"timestamp": "2025-05-15T15:43:44.745472", "level": "ERROR", "message": "Exception in TokenObtainPairView: Method \"GET\" not allowed.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "MethodNotAllowed", "value": "Method \"GET\" not allowed.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 173, in http_method_not_allowed\n    raise exceptions.MethodNotAllowed(request.method)\n", "rest_framework.exceptions.MethodNotAllowed: Method \"GET\" not allowed.\n"]}, "request_id": "c27ed524-ecbe-4cae-ad25-916bc2886e3c", "extra": {"view": "TokenObtainPairView", "request": {"method": "GET", "path": "/api/token/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "MethodNotAllowed"}}
{"timestamp": "2025-05-15T15:44:50.629906", "level": "ERROR", "message": "Exception in TokenObtainPairView: Method \"GET\" not allowed.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "MethodNotAllowed", "value": "Method \"GET\" not allowed.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 173, in http_method_not_allowed\n    raise exceptions.MethodNotAllowed(request.method)\n", "rest_framework.exceptions.MethodNotAllowed: Method \"GET\" not allowed.\n"]}, "request_id": "56ee5350-439d-4ee6-9938-2c91e307f936", "extra": {"view": "TokenObtainPairView", "request": {"method": "GET", "path": "/api/token/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "MethodNotAllowed"}}
{"timestamp": "2025-05-15T15:45:15.024678", "level": "ERROR", "message": "Exception in TokenObtainPairView: Method \"GET\" not allowed.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "MethodNotAllowed", "value": "Method \"GET\" not allowed.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 173, in http_method_not_allowed\n    raise exceptions.MethodNotAllowed(request.method)\n", "rest_framework.exceptions.MethodNotAllowed: Method \"GET\" not allowed.\n"]}, "request_id": "de2417d2-8a55-4de1-99d1-7fc998bbe995", "extra": {"view": "TokenObtainPairView", "request": {"method": "GET", "path": "/api/token/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "MethodNotAllowed"}}
{"timestamp": "2025-05-15T15:45:18.189112", "level": "ERROR", "message": "Exception in TokenObtainPairView: Method \"GET\" not allowed.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "MethodNotAllowed", "value": "Method \"GET\" not allowed.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 173, in http_method_not_allowed\n    raise exceptions.MethodNotAllowed(request.method)\n", "rest_framework.exceptions.MethodNotAllowed: Method \"GET\" not allowed.\n"]}, "request_id": "a22de36b-2b2d-4bd9-9a53-8a8dcb4e53e2", "extra": {"view": "TokenObtainPairView", "request": {"method": "GET", "path": "/api/token/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "MethodNotAllowed"}}
{"timestamp": "2025-05-15T15:45:20.036627", "level": "ERROR", "message": "Exception in TokenObtainPairView: Method \"GET\" not allowed.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "MethodNotAllowed", "value": "Method \"GET\" not allowed.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 173, in http_method_not_allowed\n    raise exceptions.MethodNotAllowed(request.method)\n", "rest_framework.exceptions.MethodNotAllowed: Method \"GET\" not allowed.\n"]}, "request_id": "3022b07d-4442-4972-8847-00e47665ee96", "extra": {"view": "TokenObtainPairView", "request": {"method": "GET", "path": "/api/token/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "MethodNotAllowed"}}
{"timestamp": "2025-05-20T06:54:36.116052", "level": "ERROR", "message": "Exception in APIRootView: Authentication credentials were not provided.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "NotAuthenticated", "value": "Authentication credentials were not provided.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 503, in dispatch\n    self.initial(request, *args, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/sentry_sdk/integrations/django/__init__.py\", line 331, in sentry_patched_drf_initial\n    return old_drf_initial(self, request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 421, in initial\n    self.check_permissions(request)\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 339, in check_permissions\n    self.permission_denied(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        request,\n        ^^^^^^^^\n        message=getattr(permission, 'message', None),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        code=getattr(permission, 'code', None)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 180, in permission_denied\n    raise exceptions.NotAuthenticated()\n", "rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.\n"]}, "request_id": "21bfda44-420a-4c70-bc28-c4ec32171281", "extra": {"view": "APIRootView", "request": {"method": "GET", "path": "/api/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "NotAuthenticated"}}
{"timestamp": "2025-05-20T15:17:50.743998", "level": "ERROR", "message": "Exception in TokenObtainPairView: Method \"GET\" not allowed.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "MethodNotAllowed", "value": "Method \"GET\" not allowed.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 173, in http_method_not_allowed\n    raise exceptions.MethodNotAllowed(request.method)\n", "rest_framework.exceptions.MethodNotAllowed: Method \"GET\" not allowed.\n"]}, "request_id": "11679e72-625e-4c20-ba1a-4b8154a163f6", "extra": {"view": "TokenObtainPairView", "request": {"method": "GET", "path": "/api/token/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "MethodNotAllowed"}}
{"timestamp": "2025-05-25T16:33:44.379830", "level": "ERROR", "message": "Exception in RegisterView: Method \"GET\" not allowed.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "MethodNotAllowed", "value": "Method \"GET\" not allowed.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 173, in http_method_not_allowed\n    raise exceptions.MethodNotAllowed(request.method)\n", "rest_framework.exceptions.MethodNotAllowed: Method \"GET\" not allowed.\n"]}, "request_id": "333f2352-c194-44d8-becf-69191c9b291a", "extra": {"view": "RegisterView", "request": {"method": "GET", "path": "/auth/registration/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "MethodNotAllowed"}}
{"timestamp": "2025-05-25T16:34:40.788382", "level": "ERROR", "message": "Exception in UserLoginView: Method \"GET\" not allowed.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "MethodNotAllowed", "value": "Method \"GET\" not allowed.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 173, in http_method_not_allowed\n    raise exceptions.MethodNotAllowed(request.method)\n", "rest_framework.exceptions.MethodNotAllowed: Method \"GET\" not allowed.\n"]}, "request_id": "58131100-7e79-472c-b4e7-7feb4e115c35", "extra": {"view": "UserLoginView", "request": {"method": "GET", "path": "/accounts/login/", "query_params": {"next": ["/auth/social/"]}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "MethodNotAllowed"}}
{"timestamp": "2025-05-25T16:34:51.941794", "level": "ERROR", "message": "Exception in GitHubLogin: Method \"GET\" not allowed.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "MethodNotAllowed", "value": "Method \"GET\" not allowed.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 173, in http_method_not_allowed\n    raise exceptions.MethodNotAllowed(request.method)\n", "rest_framework.exceptions.MethodNotAllowed: Method \"GET\" not allowed.\n"]}, "request_id": "4e4c75e5-7d55-479c-bf37-e40a44e57c3d", "extra": {"view": "GitHubLogin", "request": {"method": "GET", "path": "/auth/github/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "MethodNotAllowed"}}
{"timestamp": "2025-05-25T16:35:13.125466", "level": "ERROR", "message": "Exception in GoogleLogin: Method \"GET\" not allowed.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "MethodNotAllowed", "value": "Method \"GET\" not allowed.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 173, in http_method_not_allowed\n    raise exceptions.MethodNotAllowed(request.method)\n", "rest_framework.exceptions.MethodNotAllowed: Method \"GET\" not allowed.\n"]}, "request_id": "f7356186-10da-4056-a317-7eb98b29ce06", "extra": {"view": "GoogleLogin", "request": {"method": "GET", "path": "/auth/google/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "MethodNotAllowed"}}
{"timestamp": "2025-05-25T16:35:42.347866", "level": "ERROR", "message": "Exception in APIRootView: Authentication credentials were not provided.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "NotAuthenticated", "value": "Authentication credentials were not provided.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 503, in dispatch\n    self.initial(request, *args, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/sentry_sdk/integrations/django/__init__.py\", line 331, in sentry_patched_drf_initial\n    return old_drf_initial(self, request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 421, in initial\n    self.check_permissions(request)\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 339, in check_permissions\n    self.permission_denied(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        request,\n        ^^^^^^^^\n        message=getattr(permission, 'message', None),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        code=getattr(permission, 'code', None)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 180, in permission_denied\n    raise exceptions.NotAuthenticated()\n", "rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.\n"]}, "request_id": "c645564d-b1cd-418c-b09a-f4737de1fcd9", "extra": {"view": "APIRootView", "request": {"method": "GET", "path": "/api/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "NotAuthenticated"}}
{"timestamp": "2025-05-25T16:36:32.977546", "level": "ERROR", "message": "Exception in APIRootView: Authentication credentials were not provided.", "module": "exception_handler", "function": "custom_exception_handler", "line": 130, "exception": {"type": "NotAuthenticated", "value": "Authentication credentials were not provided.", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 503, in dispatch\n    self.initial(request, *args, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/sentry_sdk/integrations/django/__init__.py\", line 331, in sentry_patched_drf_initial\n    return old_drf_initial(self, request, *args, **kwargs)\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 421, in initial\n    self.check_permissions(request)\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 339, in check_permissions\n    self.permission_denied(\n    ~~~~~~~~~~~~~~~~~~~~~~^\n        request,\n        ^^^^^^^^\n        message=getattr(permission, 'message', None),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        code=getattr(permission, 'code', None)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n", "  File \"/Users/siddhantgupta/Desktop/SID/DJANGO/.venv/lib/python3.13/site-packages/rest_framework/views.py\", line 180, in permission_denied\n    raise exceptions.NotAuthenticated()\n", "rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.\n"]}, "request_id": "ee1c772b-b0c8-4262-9422-312bbfb73a8f", "extra": {"view": "APIRootView", "request": {"method": "GET", "path": "/api/", "query_params": {}, "content_type": "text/plain", "client": {"ip": "127.0.0.1", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"}, "user": {"id": null, "username": "", "is_authenticated": false}}, "exception_type": "NotAuthenticated"}}
